import {
  Bell,
  Book,
  Bot,
  Bug,
  Camera,
  Cloud,
  Code,
  Command,
  Compass,
  Database,
  Flame,
  FlaskConical,
  Folder,
  Gauge,
  Gift,
  GitBranch,
  Globe,
  Heart,
  History,
  House,
  LayoutGrid,
  Lightbulb,
  Link,
  Lock,
  MessageSquare,
  Monitor,
  Moon,
  Music,
  Network,
  Palette,
  Pen,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  Share2,
  Smartphone,
  Star,
  Sun,
  Tag,
  Trophy,
  Users,
  Wrench,
  Zap,
} from "lucide-react";
import type { ComponentType } from "react";

export interface ProjectIconEntry {
  key: string;
  /** 引用 global.css 中的 --pi-* 色板变量（OKLCH 等明度/彩度），随主题自动适配明暗 */
  color: string;
  Icon: ComponentType<{ style?: React.CSSProperties }>;
}

/** 新建项目时可选的内置图标（Lucide），颜色取自 --pi-* 统一色板；名称经文案 key `icon.{key}` 翻译 */
export const PROJECT_ICONS: ProjectIconEntry[] = [
  { key: "code", color: "var(--pi-blue)", Icon: Code },
  { key: "cloud", color: "var(--pi-cyan)", Icon: Cloud },
  { key: "experiment", color: "var(--pi-violet)", Icon: FlaskConical },
  { key: "bug", color: "var(--pi-red)", Icon: Bug },
  { key: "fire", color: "var(--pi-orange)", Icon: Flame },
  { key: "thunderbolt", color: "var(--pi-amber)", Icon: Zap },
  { key: "compass", color: "var(--pi-blue)", Icon: Compass },
  { key: "launch", color: "var(--pi-green)", Icon: Rocket },
  { key: "star", color: "var(--pi-amber)", Icon: Star },
  { key: "heart", color: "var(--pi-pink)", Icon: Heart },
  { key: "bulb", color: "var(--pi-amber)", Icon: Lightbulb },
  { key: "book", color: "var(--pi-teal)", Icon: Book },
  { key: "palette", color: "var(--pi-purple)", Icon: Palette },
  { key: "robot", color: "var(--pi-slate)", Icon: Bot },
  { key: "music", color: "var(--pi-pink)", Icon: Music },
  { key: "camera", color: "var(--pi-slate)", Icon: Camera },
  { key: "trophy", color: "var(--pi-amber)", Icon: Trophy },
  { key: "gift", color: "var(--pi-red)", Icon: Gift },
  { key: "apps", color: "var(--pi-green)", Icon: LayoutGrid },
  { key: "desktop", color: "var(--pi-blue)", Icon: Monitor },
  { key: "storage", color: "var(--pi-violet)", Icon: Database },
  { key: "command", color: "var(--pi-slate)", Icon: Command },
  { key: "tool", color: "var(--pi-orange)", Icon: Wrench },
  { key: "moon", color: "var(--pi-violet)", Icon: Moon },
  { key: "branch", color: "var(--pi-green)", Icon: GitBranch },
  { key: "dashboard", color: "var(--pi-blue)", Icon: Gauge },
  { key: "folder", color: "var(--pi-amber)", Icon: Folder },
  { key: "home", color: "var(--pi-red)", Icon: House },
  { key: "lock", color: "var(--pi-violet)", Icon: Lock },
  { key: "link", color: "var(--pi-cyan)", Icon: Link },
  { key: "message", color: "var(--pi-cyan)", Icon: MessageSquare },
  { key: "mindMapping", color: "var(--pi-purple)", Icon: Network },
  { key: "mobile", color: "var(--pi-blue)", Icon: Smartphone },
  { key: "notification", color: "var(--pi-orange)", Icon: Bell },
  { key: "pen", color: "var(--pi-pink)", Icon: Pen },
  { key: "public", color: "var(--pi-teal)", Icon: Globe },
  { key: "search", color: "var(--pi-blue)", Icon: Search },
  { key: "settings", color: "var(--pi-slate)", Icon: Settings },
  { key: "shareAlt", color: "var(--pi-green)", Icon: Share2 },
  { key: "sync", color: "var(--pi-cyan)", Icon: RefreshCw },
  { key: "tag", color: "var(--pi-teal)", Icon: Tag },
  { key: "sun", color: "var(--pi-amber)", Icon: Sun },
  { key: "user", color: "var(--pi-violet)", Icon: Users },
  { key: "history", color: "var(--pi-slate)", Icon: History },
];

export const DEFAULT_PROJECT_ICON = PROJECT_ICONS[0];

export function getProjectIcon(key: string): ProjectIconEntry {
  return PROJECT_ICONS.find((entry) => entry.key === key) ?? DEFAULT_PROJECT_ICON;
}
