import {
  Bell,
  Book,
  Bot,
  Bug,
  Camera,
  Cloud,
  Code,
  Command,
  Compass,
  Database,
  Flame,
  FlaskConical,
  Folder,
  Gauge,
  Gift,
  GitBranch,
  Globe,
  Heart,
  History,
  House,
  LayoutGrid,
  Lightbulb,
  Link,
  Lock,
  MessageSquare,
  Monitor,
  Moon,
  Music,
  Network,
  Palette,
  Pen,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  Share2,
  Smartphone,
  Star,
  Sun,
  Tag,
  Trophy,
  Users,
  Wrench,
  Zap,
} from "lucide-react";
import type { ComponentType } from "react";

export interface ProjectIconEntry {
  key: string;
  color: string;
  Icon: ComponentType<{ style?: React.CSSProperties }>;
}

/** 新建项目时可选的内置图标（Lucide），颜色沿用既有色板；名称经文案 key `icon.{key}` 翻译 */
export const PROJECT_ICONS: ProjectIconEntry[] = [
  { key: "code", color: "#165dff", Icon: Code },
  { key: "cloud", color: "#0fc6c2", Icon: Cloud },
  { key: "experiment", color: "#722ed1", Icon: FlaskConical },
  { key: "bug", color: "#f53f3f", Icon: Bug },
  { key: "fire", color: "#f77234", Icon: Flame },
  { key: "thunderbolt", color: "#f7ba1e", Icon: Zap },
  { key: "compass", color: "#3491fa", Icon: Compass },
  { key: "launch", color: "#00b42a", Icon: Rocket },
  { key: "star", color: "#ffb400", Icon: Star },
  { key: "heart", color: "#eb2f96", Icon: Heart },
  { key: "bulb", color: "#ff7d00", Icon: Lightbulb },
  { key: "book", color: "#14c9c9", Icon: Book },
  { key: "palette", color: "#b71de8", Icon: Palette },
  { key: "robot", color: "#165dff", Icon: Bot },
  { key: "music", color: "#eb2f96", Icon: Music },
  { key: "camera", color: "#364052", Icon: Camera },
  { key: "trophy", color: "#f7ba1e", Icon: Trophy },
  { key: "gift", color: "#f53f3f", Icon: Gift },
  { key: "apps", color: "#00b42a", Icon: LayoutGrid },
  { key: "desktop", color: "#3491fa", Icon: Monitor },
  { key: "storage", color: "#722ed1", Icon: Database },
  { key: "command", color: "#364052", Icon: Command },
  { key: "tool", color: "#f77234", Icon: Wrench },
  { key: "moon", color: "#572ab1", Icon: Moon },
  { key: "branch", color: "#00b42a", Icon: GitBranch },
  { key: "dashboard", color: "#165dff", Icon: Gauge },
  { key: "folder", color: "#f77234", Icon: Folder },
  { key: "home", color: "#f53f3f", Icon: House },
  { key: "lock", color: "#722ed1", Icon: Lock },
  { key: "link", color: "#3491fa", Icon: Link },
  { key: "message", color: "#0fc6c2", Icon: MessageSquare },
  { key: "mindMapping", color: "#b71de8", Icon: Network },
  { key: "mobile", color: "#3491fa", Icon: Smartphone },
  { key: "notification", color: "#ff7d00", Icon: Bell },
  { key: "pen", color: "#eb2f96", Icon: Pen },
  { key: "public", color: "#14c9c9", Icon: Globe },
  { key: "search", color: "#165dff", Icon: Search },
  { key: "settings", color: "#4e5969", Icon: Settings },
  { key: "shareAlt", color: "#00b42a", Icon: Share2 },
  { key: "sync", color: "#0fc6c2", Icon: RefreshCw },
  { key: "tag", color: "#f7ba1e", Icon: Tag },
  { key: "sun", color: "#f7ba1e", Icon: Sun },
  { key: "user", color: "#572ab1", Icon: Users },
  { key: "history", color: "#86909c", Icon: History },
];

export const DEFAULT_PROJECT_ICON = PROJECT_ICONS[0];

export function getProjectIcon(key: string): ProjectIconEntry {
  return PROJECT_ICONS.find((entry) => entry.key === key) ?? DEFAULT_PROJECT_ICON;
}
